trigger:
  - master
  - feat/*
  - fix/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscriptionEndpoint: $(service-connection-name)
  azureContainerRegistry: $(container-registry-host)
  registryName: $(azureContainerRegistry)/$(Build.Repository.Name)
  # imageTag: $(registryName):$(Build.BuildId)-$(Build.SourceVersion)

stages:
- stage: Tests
  displayName: 'Test'
  jobs:
    - job: Dependencies Audit
      steps:
      - script: npm audit
        displayName: npm audit
        continueOnError: true

    - job: npm
      steps:
      - script: npm ci
        displayName: npm install

      - script: npm run lint
        displayName: Lint Code

      - script: npm run test:unit
        displayName: Unit Tests

      - script: npm run build
        displayName: Build Assets

      - publish: $(System.DefaultWorkingDirectory)/dist
        artifact: dist

# ----------------------------
# Docker Image: Build and Push
# ----------------------------

- stage: BuildImage
  displayName: 'Build'
  jobs:
    - job: BuildStatic
      displayName: Build and Push Image
      steps:
      - script:  echo '##vso[task.setvariable variable=sha]'$(git rev-parse --short HEAD)''
        displayName: 'Set sha variable'

      - download: current
        artifact: dist
        displayName: 'test download'

      - script: ls -a dist/
        displayName: list dist

      - script: echo $(sha)
        displayName: 'output commit sha carries over jobs?'

      # - script: docker build --tag $(registryName):$(Build.BuildId)-${sha} .
      #   displayName: 'Docker: Build and tag image'

      # - task: Docker@1
      #   displayName: 'Push an image'
      #   inputs:
      #     azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      #     azureContainerRegistry: $(azureContainerRegistry)
      #     imageName: $(imageTag)
      #     command: push
