trigger:
  - master
  - feat/*
  - fix/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscriptionEndpoint: $(service-connection-name)
  azureContainerRegistry: $(container-registry-host)
  registryName: $(azureContainerRegistry)/$(Build.Repository.Name)
  # imageTag: $(registryName):$(Build.BuildId)-$(Build.SourceVersion)

stages:
- stage: Tests
  displayName: 'Test'
  jobs:
    - job: Audit
      steps:
      - script: npm audit
        displayName: Audit Dependencies
        continueOnError: true

    - job: Linter
      steps:
      - script: npm ci && npm run lint
        displayName: Lint Code

    - job: UnitTests
      displayName: Unit Tests
      steps:
      - script: npm ci && npm run test:unit
        displayName: Unit Tests

# ----------------------------
# Docker Image: Build and Push
# ----------------------------

- stage: BuildImage
  displayName: 'Build'
  jobs:
    - job: Build
      displayName: Build and Push Image
      steps:
      - script: npm ci && npm run build
        displayName: 'Build HTML/JS/CSS'

      - script: echo '##vso[task.setvariable variable=commitSha]'$(git rev-parse --short HEAD)''
        displayName: 'Set commitSha variable'

      - script: docker build --tag $(registryName):$(Build.BuildId)-${commitSha} .
        displayName: 'Docker: Build and tag image'

      # - task: Docker@1
      #   displayName: 'Push an image'
      #   inputs:
      #     azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      #     azureContainerRegistry: $(azureContainerRegistry)
      #     imageName: $(imageTag)
      #     command: push
